### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by hvanmaanen** [cbeneke/hcloud-fip-controller#27]
I've created a Helm chart, don't know if you're interested in that, if so where do you want the helm chart.

**Comment by cbeneke** [comment]
Definitely interested :) Do you want to support the chart further?

I'm fine with putting it along the code (e.g. a `helm` folder in the top level) or in a separate repository under your control (then I'd just add a comment & link in the README). Whichever suits your needs better.

**Comment by Xerceng** [comment]
I think a seperate repository is most suiting for helm charts. Have a look at this example: https://helm.sh/docs/topics/chart_repository/#github-pages-example and this: https://github.com/technosophos/tscharts

A good name for the repository would be "charts" so that the url will become: https://cbeneke.github.com/charts

If you can provide that repository I would be willing to setup this and maintain the chart.

**Comment by cbeneke** [comment]
I've created a repo at https://github.com/cbeneke/helm-charts .. feel free to open a PR there :) Thanks in advance!

If you can't maintain it, I'm fine with taking over there too, but as I've enough workload too currently, it will still be just best effort.
