### ISSUE TITLE
leaseDuration must be greater than renewDeadline

### ISSUE THREAD

**Issue by xinomahc** [cbeneke/hcloud-fip-controller#44]
`panic: leaseDuration must be greater than renewDeadline`

is there a purpose for this or?

sorry for noob question, fairly new to kubernetes 😅

**Comment by phiphi282** [comment]
This error is coming from the kubernetes leaderelection.

The leaseDuration is the duration that non-leaders must wait before acquiring a lease and the renewDeadline is the duration the leader will try to renew the leadership.

Because of this. the leaseDuration must be greater than the renewDeadline, because otherwise multiple leaders would become possible.

However, the renewDeadline is currently static in the fip-controller. I guess I will create a pull-request soon, to either make the renewDeadline depend on the leaseDuration or make it another configuration variable.
