### ISSUE TITLE
Fip controller extension to volume controller

### ISSUE THREAD

**Issue by PCatinean** [cbeneke/hcloud-fip-controller#47]
Not sure how I can tag this as a wishlist/question but I just noticed that if a pod goes down the volumes remain attached to the node indefinitely. I think it would be an amazing feature to extend the current features of the controller to support volume un-assignment from the defunct node so CSI can pick the proper candidate. What do you think or should this be more a proposition done on the hetzner csi repo?

**Comment by cbeneke** [comment]
Hey, volume management is/should be done by the CSI provider.
Side note: Does this happen in general in your cluster? Because it should not (if it does please check the logs of the CSI controller). If you have problems with the controller please ask in the respective channels :)

Closing here for out of scope
